#!/usr/bin/env php

<?php

/*
  TODO This needs to be refactored into a proper object, instead of this $GLOBALS crap
*/
$GLOBALS['SG_TASKS'] = array(
  'help' => 'sgTaskHelp',
  'init-project' => 'sgTaskInitProject',
  'cc' => 'sgTaskClearCache',
);

if (!isset($argv[1])) {
  sgTaskHelp();
}
else if (isset($GLOBALS['SG_TASKS'][$argv[1]]))
{
  $GLOBALS['SG_TASKS'][$argv[1]]();
}
else
{
  sgMessage('Command "' . $argv[1] . '" does not exist. Run "superglue help" to get a list of available commands.');
}
fputs(STDOUT, "\r\n");


function sgTaskHelp()
{
  $message = "Available commands:";
  foreach ($GLOBALS['SG_TASKS'] as $name => $task) {
    $message .= "\r\n  " . $name;
  }
  sgMessage($message);
}

/*
  TODO make this more generic
*/
function sgTaskClearCache()
{
  _removeCacheFiles(getcwd() . '/cache');
  _removeCacheFiles(getcwd() . '/cache/templates');
  sgMessage('Cache cleared');
}

function _removeCacheFiles($path) {
  $files = scandir($path);
  foreach ($files as $filename) {
    $file = realpath($path . '/' . $filename);
    $extension = pathinfo($file, PATHINFO_EXTENSION);
    if ($extension == 'cache' || $extension == 'php') {
      sgMessage('Removing: ' . $file);
      unlink($file);
    }
  }
}

function sgTaskInitProject()
{
  $targetDir = getcwd();
  $scriptDir = realpath(dirname(__FILE__));
  
  sgConfirm('Are you sure you want to initialize a new project in "' . $targetDir .'"?');
  
  if (file_exists($targetDir . '/superglue')) {
    sgMessage('A project already exists in this directory.');
    return;
  }
  
  sgMessage('Initializing project...');
  mkdir($targetDir . '/config', 0755);
  mkdir($targetDir . '/cache', 0777);
  chmod($targetDir . '/cache', 0777);
  mkdir($targetDir . '/cache/templates', 0777);
  chmod($targetDir . '/cache/templates', 0777);
  mkdir($targetDir . '/models', 0755);
  mkdir($targetDir . '/controllers', 0755);
  mkdir($targetDir . '/views', 0755);
  mkdir($targetDir . '/web', 0755);
  copy($scriptDir . '/skeleton/web/htaccess-dist', $targetDir . '/web/.htaccess');
  copy($scriptDir . '/skeleton/web/index.php-dist', $targetDir . '/web/index.php');
  copy($scriptDir . '/skeleton/config/ProjectConfiguration.class.php-dist', $targetDir . '/config/ProjectConfiguration.class.php');
  copy($scriptDir . '/skeleton/config/config.php-dist', $targetDir . '/config/config.php');
  copy($scriptDir . '/skeleton/config/routing.php-dist', $targetDir . '/config/routing.php');
  symlink(realpath(__FILE__), $targetDir . '/superglue');
  chmod($targetDir . '/superglue', 0755);
  sgMessage('Finished initializing project.');
}

/*
  TODO add ANSI color support
*/
function sgMessage($string)
{
  fputs(STDOUT, $string . "\r\n");
}

function sgConfirm($string)
{
  sgMessage($string . ' (y/N)');
  $confirm = fgets(STDIN);
  fputs(STDOUT, "\r\n");
  if (trim($confirm) == 'y') {
    return true;
  }
  fputs(STDOUT, 'Cancelled.' . "\r\n\r\n");
  exit(0);
}
