#!/usr/bin/env php

<?php
set_exception_handler(create_function('$e', 'sgCLI::handleException($e);'));

$path = realpath(dirname($_SERVER['PHP_SELF']));
if (file_exists($path . '/config/ProjectConfiguration.class.php'))
{
  require_once($path . '/config/ProjectConfiguration.class.php');
  ProjectConfiguration::getInstance();
}
else
{
  require_once($path . '/sgAutoloader.class.php');
  sgAutoloader::register();
  sgConfiguration::getInstance();
}

sgCLI::getInstance()->execute();
sgCLI::shutdown();